config/routes.rb
Uboard::Application.routes.draw do
  
  devise_for :admins, :controllers => { :registrations => "registrations" }
  resources :posts do
    member do
      get 'preview'
    end
    collection do
      get "show_more"
      get 'search'
      post 'search'
      get 'tags'
      put 'image_preview'
      post 'image_preview'
    end
  end
  resources :posts
  resources :comments
  
  match 'chat' => 'chat#index'
  match 'chat/send' => 'chat#send_msg'
  
  root :to => 'posts#index'
  

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    attr_accessible :author, :message, :post_id
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :image, :post_id
  belongs_to :post
  has_attached_file :image,
    :styles => { :large => "640x480", :thumb => "100x100>" },
    :storage => :dropbox,
    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
    :path => "/uboard/:rails_env/:attachment/:id/:style/:filename"

  validates_attachment_size :image, :less_than => 2.megabytes
  validates_attachment_content_type :image, :content_type => ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :author, :content, :title, :images_attributes, :tag_list
  has_many :images
  accepts_nested_attributes_for :images, :allow_destroy => true

  acts_as_taggable
  
  def self.search(search)
    if search
      find(:all, :conditions => 
        ['author LIKE :search OR title LIKE :search OR content LIKE :search',
          { :search => "%#{search}%"} ])
    else
      find(:all)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def user_posts
    session[:user_posts]
  end

  def can_edit?
    !user_posts.nil? && user_posts.member?(@post.id)
  end

  def assign_post
    @post_id = params[:id]
    @post = Post.find(@post_id)
    @editable = can_edit? || admin_signed_in?
  end
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  
  def index
    
  end
  
  def send_msg
    Pusher['test_channel'].trigger('message', {
      :message => params[:message]
    })
    render :partial => 'blank'
  end
 
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new

  end

  def index
      
  end
  
  def create
      Comment.create!(params[:comment])
      redirect_to post_path(params[:comment][:post_id])
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index  

    session[:posts_showed] = 2
    @posts_showed = session[:posts_showed]

    @include_tags = session[:include_tags].nil? ? [] : session[:include_tags]
    @exclude_tags = session[:exclude_tags].nil? ? [] : session[:exclude_tags]
    @include_tags -= @exclude_tags if !@include_tags.nil?
    @exclude_tags -= @include_tags if !@exclude_tags.nil?

    @all_tags = Post.tag_counts_on(:tags)

    @posts = Post.all
    session[:post] = nil
  end
  
  def show
    assign_post

    @comment = Comment.new
    @comments = Comment.where(:post_id => @post.id).all
  end

  def new
    @tags = Post.tag_counts_on(:tags)
    if session[:post].nil?
      @post = Post.new
    else
      @post = Post.new(session[:post])
    end
    @post.images.build
  end
  
  def create
    #session[:post] = params[:post].except(:images)
    if !admin_signed_in? && !verify_recaptcha
      flash[:warning] = "Wrong captcha"
      redirect_to new_post_path
      return
    end
    @post = Post.new(params[:post])
    if @post.save
      flash.keep[:notice] = "Post was successfully created."
      session[:post] = nil
      if session[:user_posts].nil?
        session[:user_posts] = [@post.id]
      else
        session[:user_posts].insert(0, @post.id)
      end
      redirect_to @post
    else
      render :action => 'new'
    end
  end
  
  def edit
    assign_post
    @tags = Post.tag_counts_on(:tags)
    if !@editable
      flash[:warning] = "Not your post to edit"
      redirect_to @post
    end
    @post.images.build
  end

  def update
    assign_post
    # session[:post] = params[:post].except(:images)

    if !admin_signed_in? && !verify_recaptcha
      flash[:warning] = "Wrong captcha"
      redirect_to edit_post_path(@post)
      return
    end


    if @editable && @post.update_attributes(params[:post])
      flash[:notice] = "Successfully updated post"
      redirect_to post_url
    else
      flash[:notice] = "Something gone wrong!"
      redirect_to post_url
    end
    
  end

  def destroy
    assign_post
    if !@editable
      flash[:warning] = "Don't touch it!"
      redirect_to @post
    end
    if @post.destroy
        flash[:notice] = "Successfully deleted post"
        redirect_to posts_url
    else
      render :action => "delete"
    end
  end

  def preview
    @post_id = params[:id]
    @post = Post.find(@post_id)
    respond_to do | format |
        format.js {render :layout => false}
        format.html {render :partial => "preview", :layout => false}
    end
  end

  def image_preview
    if params[:post][:images_attributes].nil?
      render :partial => "blank"
    else
      @last_image_field_id = 0
      @images = params[:post][:images_attributes].reject {|k,v| v.has_key? "_destroy"}
        .map {|k,v|
          file = v["image"]
          if k.to_i > @last_image_field_id
            @last_image_field_id = k.to_i
          end
          {:filename => file.original_filename, :uri => "data:" + file.content_type +
              ";base64," + Base64.encode64(file.tempfile.read) }
      }
      @new_field_id = "post_images_attributes_#{@last_image_field_id+1}_image"
      @new_field_name = "post[images_attributes][#{@last_image_field_id+1}][image]"
      render :partial => "image_preview", :layout => false
    end
    
    
  end

  def search
    
    @search = params[:search]
    @include_tags = session[:include_tags]
    @exclude_tags = session[:exclude_tags]

    if !@include_tags.nil? && !@include_tags.empty?
      @posts = Post.tagged_with(@include_tags, :any => true)
    else
      @posts = Post
    end
    if !@exclude_tags.nil? && !@exclude_tags.empty?
      @posts = @posts.tagged_with(@exclude_tags, :exclude => true)
    end
    @posts = @posts.search(@search)
    
    @posts_showed = session[:posts_showed]
    
    render :partial => 'list'
  end

  def tags

    include_tag = params[:include_tag]
    exclude_tag = params[:exclude_tag]

    @include_tags = session[:include_tags].nil? ? [] : session[:include_tags]
    @exclude_tags = session[:exclude_tags].nil? ? [] : session[:exclude_tags]

    if !include_tag.nil?
      if !@include_tags.member?(include_tag)
        @include_tags.push(include_tag)
      else
        @include_tags.delete(include_tag)
      end
    end
    if !exclude_tag.nil?
      if !@exclude_tags.member?(exclude_tag)
        @exclude_tags.push(exclude_tag)
      else
        @exclude_tags.delete(exclude_tag)
      end

    end

    session[:include_tags] = @include_tags
    session[:exclude_tags] = @exclude_tags

    @all_tags = Post.tag_counts_on(:tags)

    render :partial => 'tags', :locals =>
      { :all_tags => @all_tags, :include_tags => @include_tags, :exclude_tags => @exclude_tags}
  end

  def show_more
     session[:posts_showed] = session[:posts_showed] + 2
     render :partial => "blank"
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  prepend_before_filter :require_no_authentication, :only => [ :cancel ]
  def new
    if Admin.exists? && !admin_signed_in?
      flash[:notice] = "Sign in first to sign up the new admin"
      redirect_to "/admins/sign_in"
    else
      super
    end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
  def admin_exists?
    Admin.exists?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/chat/index.html.haml
= javascript_include_tag "http://js.pusher.com/1.12/pusher.min.js"

:javascript
  var pusher = new Pusher('#{Pusher.key}'); // uses your API KEY
  var channel = pusher.subscribe('test_channel');

  $(function(){
    var history = [], idx = 0;
    $("#message").focus();

    $(window).bind("focus", function(){
      $("#message").focus();
    });

    var logpanel = $("#log");

    function sendmsg(){
      var msg = $("#message").val();
      history.unshift(msg);
      idx = 0;
      $("#message").val("");
    };

    $("#log").bind('click', function(){
      $("#message").focus()
    });

    $("#sendbtn").bind("click", function(){
      sendmsg();
      $("#message").focus()
    });

    $("#message").bind("keydown", function(e){
      if(e.which == 13){
        sendmsg();
      }
    });


    function scrollToBottom() {
        window.scrollBy(0, document.body.scrollHeight - document.body.scrollTop);
    };

    function log(data){
      logpanel.append("<p>"+data+"</p>");
      scrollToBottom();
    };

    channel.bind('message', function(data) {
      log(data.message);
    });
 
  });

= form_tag url_for(:controller => 'chat', :action => 'send_msg'), :class => 'form', :remote => true do
  .control-group
    = label_tag "msg", "Message:", :class => 'control-label'
    .controls
      = text_field_tag "input", "", :name => 'message', :id => 'message'
  .control-group
    .controls
      = submit_tag 'Send', :class => 'btn', :id => 'send'

#log

app/views/comments/index.html.haml
- if @comments.empty?
	%div= "No comments yet. Make some, fucka!"
- else
	%table#comments
		%tbody
			- @comments.each do |comment|
				%tr
					%td= comment.author 
					%td= comment.message
					%td= comment.created_at

app/views/comments/new.html.haml
= form_for @comment, :html => {:class => "form-horizontal"} do |f|
  = f.hidden_field :post_id, :value => @post.id
  .control-group
    .control-label
      = f.label "Author"
    .controls
      = f.text_field :author
  .controls
    = f.text_area :message, :rows => 3
  .controls
    = f.submit "Comment"

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "U-board", root_path, :class => 'brand'
%ul.nav
  %li
    = link_to "New Post", new_post_path
  %li
    - if !admin_exists?
      = link_to "Sign up", new_admin_registration_path
    - elsif admin_signed_in? 
      = link_to "Sign out", destroy_admin_session_path, :method => :delete
    - else
      = link_to "Sign in", new_admin_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "U-board"
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield(:head)
        
  %body
    #wrap
      %header.navbar.navbar-fixed-top
        %nav.navbar-inner
          .container
            = render 'layouts/navigation'

      #main{:role => "main"}
        .container
          .content
            .row
              .span12
                = render 'layouts/messages'
                = yield
      #push

    #footer
      .container
        %p.credit
          =link_to "Herp&Derp", "mailto:uboarders@gmail.com"
      

app/views/posts/_chat.html.haml
= javascript_include_tag "http://js.pusher.com/1.12/pusher.min.js"

:javascript
  var pusher = new Pusher('#{Pusher.key}'); // uses your API KEY
  var channel = pusher.subscribe('test_channel');

  $(function(){
    var history = [], idx = 0;
    $("#message").focus();

    $(window).bind("focus", function(){
      $("#message").focus();
    });

    var logpanel = $("#log");

    function sendmsg(){
      var msg = $("#message").val();
      history.unshift(msg);
      idx = 0;
      $("#message").val("");
    };

    $("#log").bind('click', function(){
      $("#message").focus()
    });

    $("#sendbtn").bind("click", function(){
      sendmsg();
      $("#message").focus()
    });

    $("#message").bind("keydown", function(e){
      if(e.which == 13){
        sendmsg();
      }
    });


    function scrollToBottom() {
        window.scrollBy(0, document.body.scrollHeight - document.body.scrollTop);
    };

    function log(data){
      logpanel.append("<p>"+data+"</p>");
      scrollToBottom();
    };

    channel.bind('message', function(data) {
      log(data.message);
    });
 
  });

= form_tag url_for(:controller => 'chat', :action => 'send_msg'), :class => 'form', :remote => true do
  .control-group
    = label_tag "msg", "Message:", :class => 'control-label'
    .controls
      = text_field_tag "input", "", :name => 'message', :id => 'message'
  .control-group
    .controls
      = submit_tag 'Send', :class => 'btn', :id => 'send'

#log

app/views/posts/_form.html.haml
= form_for @post, :html => { :multipart => true, :id => "post_form", :class => "form-horizontal" } do |f|
  .control-group
    .control-label
      = f.label "Title"
    .controls
      = f.text_field :title
  .control-group
    .control-label
      = f.label "Author"
    .controls
      = f.text_field :author
  .control-group
    .control-label
      = f.label "Tags"
    .controls
      = f.text_field :tag_list, :id => 'tags'

  .controls
    = f.text_area :content, :id => 'editor', :spellcheck => 'true'
  .control-group
    .controls
      = f.fields_for :images do |image_field|
        #image_field
          - if image_field.object.new_record?    
            = image_field.file_field :image, :class => "image_file_field"
          - else
            = link_to image_tag(image_field.object.image.url(:thumb)), image_field.object.image.url(:original), :rel => "prettyPhoto"
            = image_field.label "Delete?"
            = image_field.check_box :_destroy
      #new_image_field
  
      %iframe#image_preview{:name => "image_preview", :seamless => "true", :scrolling => "no", :width => "100%", :style => "height: 0"}

  .controls
    = recaptcha_tags
  .controls
    = f.submit



- tags = ActsAsTaggableOn::Tag.all
- a = []
- tags.each {|t| a << t.name }
:javascript
  jQuery(function($) {
    $("#editor").jqte();

    var availableTags = #{a};

    function split( val ) {
            return val.split( /,\s*/ );
    }
    function extractLast( term ) {
            return split( term ).pop();
    }
    $( "#tags" ).bind( "keydown", function( event ) {
      if ( event.keyCode === $.ui.keyCode.TAB &&
                      $( this ).data( "autocomplete" ).menu.active ) {
              event.preventDefault();
      }
    }).click(function() {
      $(this).autocomplete('search', $(this).val())
    })
    $( "#tags" ).autocomplete({
      minLength: 0,
      source: function( request, response ) {
              // delegate back to autocomplete, but extract the last term
              response( $.ui.autocomplete.filter(
                      availableTags, extractLast( request.term ) ) );
      },
      autoFocus: true,
      select: function( event, ui ) {
              var terms = split( this.value );
              // remove the current input
              terms.pop();
              // add the selected item
              terms.push( ui.item.value );
              // add placeholder to get the comma-and-space at the end
              terms.push( "" );
              this.value = terms.join( ", " );
              return false;
      }

    });


    $(".image_file_field").change(function () {
      var form = $('form');

      form.prop("action", "#{image_preview_posts_path}");
      form.prop("target", "image_preview");

      form.submit();

      form.prop('action', "#{controller.action_name == 'new' ? posts_path : post_path}");
      form.prop("target", "_self");

    });

    $('iframe#image_preview').load(function()
    {
        
        var iframe =  $('iframe#image_preview');
        iframe.contents().find("a[rel^='prettyPhoto']").prettyPhoto({social_tools: false, theme: 'light_square'});
        iframe[0].style.height = "20%";
    });

    

  });

  

app/views/posts/_image_preview.html.haml
- @images.each do |image|
  = link_to image_tag(image[:uri], :height => "90%"), image[:uri], :rel => "prettyPhoto"

:javascript
  parent.$("#new_image_field").before("<div id=image_field_#{@new_field_id}><input id=#{@new_field_id} name=#{@new_field_name} type=file></div>");
  parent.$("#image_field_#{@new_field_id}").change(function () {
    parent.$(".image_file_field").change();
  });

app/views/posts/_list.html.haml
- @posts.take(@posts_showed).each do |post|
  %tr
    %td
      .row-fluid
        .span2
          = post.author
        .span3
          = link_to post.title, post_path(post)
        .span2
          %time
            = post.created_at.to_date
        .span2
          = post.tag_list
        .span1
          = link_to "Preview", preview_post_path(:id => post.id), :remote => true
      .row
        .span8
          .collapse{ :id => "more#{post.id}" }

app/views/posts/_preview.html.haml
= raw @post.content
- @post.images.each do |image_field|
  = link_to image_tag(image_field.image.url(:thumb)), image_field.image.url(:original), :rel => "prettyPhoto", :id =>1

:javascript
  $("a[rel^='prettyPhoto']").prettyPhoto({social_tools: false, theme: 'light_square'});

app/views/posts/_search.html.haml
= form_tag url_for(:action => 'search'), :class => 'form-search', :id => 'search_form', :remote => true do
  .input-prepend
    = submit_tag 'Search', :class => 'btn', :id => 'search_button'
    = text_field_tag :search, params[:search], :class => 'span2 search-query', :id => 'search_field', :autofocus => true

app/views/posts/_tags.html.haml
- tag_cloud(@all_tags, {}) do |tag, css_class|
  %a.btn.btn-mini{:href => tags_posts_path(:include_tag => tag.name), "data-remote" => true}
    -if @include_tags.member?(tag.name) 
      %i.icon-ok-circle
    = tag.name
  %a.btn.btn-mini{:href => tags_posts_path(:exclude_tag => tag.name), "data-remote" => true}  
    -if @exclude_tags.member?(tag.name) 
      %i.icon-remove
    -else
      %i.icon-ok
    


  
  

app/views/posts/edit.html.haml
= render "form"

app/views/posts/index.html.haml
.row
  .span1
    .container
      #tags
        = render "tags"

  .span9
    .offset6
      = render "search"   

    .row-fluid
      .span2
        Author
      .span3
        Title
      .span2
        Time
      .span2
        Tags
      .span1
    %table.table.table-striped#list
      = render "list"
      #more_posts
    .pager
      = link_to "Show more", show_more_posts_path, :class => 'next', :id => "show_more", :remote => true

  .span2
    = render 'chat'

app/views/posts/new.html.haml
= render "form"

app/views/posts/preview.js.haml
var div = $('#more#{@post.id}');

div.html("#{j render :partial => 'preview', :locals => { :post => @post} }");

//div.slideToggle('slow');
div.collapse('toggle');

app/views/posts/show.html.haml
.row
  .span2
    %b
      = @post.title
  .span10
    = raw @post.content
.row 
  .span2
    = "author: #{@post.author}"
  .span10
    = "tags: #{@post.tag_list}"

- @post.images.each do |image_field|
  = link_to image_tag(image_field.image.url(:thumb)), image_field.image.url(:original), :rel => "prettyPhoto"
- if @editable
  = link_to "Edit", edit_post_path(@post)
  = link_to "Delete", post_path(@post), :method => :delete
= render :template => "/comments/new"
= render :template => "/comments/index"